steps:
  # ==========================================
  # 1. Build & Push Spring Boot (Java)
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-java'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/springboot-app:$SHORT_SHA', '.']
    dir: 'backend-java'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-java'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/springboot-app:$SHORT_SHA']
    waitFor: ['build-java']

  # ==========================================
  # 2. Build & Push FastAPI (Python)
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-python'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/fastapi-app:$SHORT_SHA', '.']
    dir: 'backend-python'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-python'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/fastapi-app:$SHORT_SHA']
    waitFor: ['build-python']

  # ==========================================
  # 3. Build & Push React (Frontend)
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-react'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/react-app:$SHORT_SHA', '.']
    dir: 'frontend-react'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-react'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/react-app:$SHORT_SHA']
    waitFor: ['build-react']

  # ==========================================
  # 4. Binary Attestation (SIGNING THE IMAGES)
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'sign-images'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e # Fail immediately if any command errors out
        echo "Starting Signing Process..."
        
        # Loop through all 3 images and sign them
        for IMAGE in springboot-app fastapi-app react-app; do
          
          # Use $$ to escape the variable for Cloud Build
          echo "Signing $$IMAGE..."
          
          # Get the full Digest (SHA256)
          DIGEST=$$(gcloud container images describe us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/$${IMAGE}:$SHORT_SHA --format='get(image_summary.digest)')
          
          # Sign the Digest
          gcloud beta container binauthz attestations sign-and-create \
              --project=$PROJECT_ID \
              --artifact-url="us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/$${IMAGE}@$${DIGEST}" \
              --attestor=production-attestor \
              --attestor-project=$PROJECT_ID \
              --keyversion-project=$PROJECT_ID \
              --keyversion-location=us-central1 \
              --keyversion-keyring=binauthz-keys \
              --keyversion-key=codelab-signer \
              --keyversion=1
        done
        echo "All images signed successfully."
    waitFor: ['push-java', 'push-python', 'push-react']

  # ==========================================
  # 5. Create Release in Cloud Deploy (CD)
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'trigger-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating Cloud Deploy Release..."
        gcloud deploy releases create release-$SHORT_SHA \
          --project=$PROJECT_ID \
          --region=us-central1 \
          --delivery-pipeline=microservices-pipeline \
          --images=springboot-app=us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/springboot-app:$SHORT_SHA \
          --images=fastapi-app=us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/fastapi-app:$SHORT_SHA \
          --images=react-app=us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/react-app:$SHORT_SHA
    waitFor: ['sign-images']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/springboot-app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/fastapi-app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/microservices-repo/react-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY